// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPEpHQq9KeQdCJqz9hX2S7Ia42S_0IAfU',
    appId: '1:974251765624:android:b0fe7c0a1785810759a28d',
    messagingSenderId: '974251765624',
    projectId: 'xspin-noti',
    storageBucket: 'xspin-noti.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5TNGNihTTM-wEd6vKHqFxYrOjYvYmoHk',
    appId: '1:974251765624:ios:9b604abea2a0540559a28d',
    messagingSenderId: '974251765624',
    projectId: 'xspin-noti',
    storageBucket: 'xspin-noti.firebasestorage.app',
    iosBundleId: 'com.example.xspinNoti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyyTkJBlaGHNDIIqRznsI409nSYqCEhWE',
    appId: '1:974251765624:web:01af40437b36de0959a28d',
    messagingSenderId: '974251765624',
    projectId: 'xspin-noti',
    authDomain: 'xspin-noti.firebaseapp.com',
    storageBucket: 'xspin-noti.firebasestorage.app',
    measurementId: 'G-BLY6GNSY56',
  );
}
